### ISSUE TITLE
About training time and compute specifications

### ISSUE THREAD

**Issue by SapanaChaudhary** [luckeciano/transformers-metarl#2]
Hi, thanks for sharing the repo! 

I was wondering what were the run time like for Mujoco tasks (HC and AntDir)? It looks like the paper uses number_of_layers=4 and number_of_attention_heads=16 with input size=512, which makes the transformer model huge.

**Comment by luckeciano** [comment]
Hello @SapanaChaudhary,

The input size is not 512. If you take a look at the hyperparameters from the README, the input size is 5 for most of the experiments. 512 is the dimension of the feedforward network that composes the transformer layer.

I don't remember exactly the runtime, but for HC is something like several hours (but less than a day). It is indeed more costly than RNN variants (since the transformer is more costly to run), but doable in a single-GPU setting.
