### ISSUE TITLE
About Trainning in MuJoCo HalfCheetahVelEnv

### ISSUE THREAD

**Issue by SongJianHIT** [luckeciano/transformers-metarl#3]
Thank you for sharing this repository! 
When training in the MuJoCo environment, I found that the algorithm's performance would suddenly drop at certain times. Have you ever encountered this? How did you solve it? Is this caused by the Transformer?
Looking forward to your reply! Thank you!

**Comment by luckeciano** [comment]
Hello @SongJianHIT !

I do not recall having such sudden drops, at least with the configuration provided by this repository. Keep in mind that if you have any changes in the hyperparameters, this could potentially cause these discrepancies - especially because PPO is very sensitive to any hyperparameter modification. Also make sure you are using the same versioning of MuJoCo and other libraries.

**Comment by SongJianHIT** [comment]
Okay, thank you for your reply! I will try a few more times myself.
